### ISSUE TITLE
Public marketing page for new Hubot

### ISSUE THREAD

**Issue by joeyguerra** [hubot-new/hubot#36]
I enabled pages on this repo but the /docs folder only has markdown files. They'd need to be converted to HTML files for this to work (I think).

@xurizaemon what are you thoughts on setting a public site on Github pages for this repo?

**Comment by xurizaemon** [comment]
I think it's a good step to take, but probably waits until we are prepared to make the leap.

For now I think we've tried communicating with the core team (hubotio/hubot#1541) and we've decided that they aren't responding. We currently are working on getting a repo into a state we could fork - but if the maintainers came back and re-engaged, our WIP could be something they could merge back upstream and carry on with.

OTOH if we rename/rebrand hubot at this point, the changes diverge in ways which don't contribute back easily. For that reason I'd hold off on changes which push us towards doing "branding" work in the interim, since that might be discarded.

When we do want to make a pages site of it, I expect we'll need to add an SSG to the mix to turn `docs/index.md` into `.html`, and so on. (I'm loving 11ty at the moment, but for this MkDocs or Sphinx would be fine too.)

I think the existing docs at https://github.com/hubot-new/hubot/tree/master/docs are fine for now, happy to help make a proper site of them in future, but I'm not sure we should prioritise it yet?
